# Generated by Django 5.2.9 on 2025-12-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('udemy', 'Udemy'), ('youtube', 'YouTube'), ('coursera', 'Coursera'), ('other', 'Other')], max_length=50)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('course', 'Course'), ('article', 'Article')], max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='started', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True)),
                ('certification', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('main_point', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.category')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note', models.TextField(blank=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='skills.skill')),
            ],
        ),
    ]
