# Generated by Django 5.2.9 on 2025-12-19 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='certification',
        ),
        migrations.AddField(
            model_name='skill',
            name='custom_platform',
            field=models.CharField(blank=True, help_text="Fill this only if platform is 'Other'", max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('course', 'Course'), ('article', 'Article'), ('exam', 'Exam'), ('mixed', 'Mixed')], max_length=50),
        ),
    ]
