# Generated by Django 5.2.9 on 2025-12-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_skill_certification_skill_custom_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='learning_type',
            field=models.CharField(choices=[('course', 'Course'), ('tutorial', 'Tutorial'), ('certification', 'Certification')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
