# Generated by Django 5.2.9 on 2025-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_learning_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='learning_type',
            field=models.CharField(choices=[('course', 'Course'), ('tutorial', 'Tutorial'), ('certification', 'Certification')], default='course', max_length=50),
        ),
    ]
